### ISSUE TITLE
Looking forward to the code

### ISSUE THREAD

**Issue by UCASHurui** [TomerRonen34/mixed-resolution-vit#1]
Congrats on your excellent work being accepted. I am looking forward to the official implementation. Thanks in advance.

**Comment by TomerRonen34** [comment]
I'm glad you liked it! The official code will be out sometime during May, but I can share specific parts earlier if you wish.

**Comment by UCASHurui** [comment]
That will be great! Any content that could be shared earlier will be appreciated!

**Comment by damonwan1** [comment]
Waiting for the official codes.

**Comment by TomerRonen34** [comment]
First release is out :)
