### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Walid-Ahmed** [TomerRonen34/mixed-resolution-vit#3]
Thanks a lot for the great repo

  I keep getting errors related to  "TypeError: 'type' object is not subscriptable"

File "../mixed_res/patch_scorers/patch_scorer.py", line 52, in PatchScorer
    ) -> list[list[float]]:
TypeError: 'type' object is not subscriptable

Can you please help me?

**Comment by TomerRonen34** [comment]
I'm glad you like it :)
What code are you running that uses a patch scorer?
Do the example notebooks work for you?

**Comment by Walid-Ahmed** [comment]
Thanks!
I am using  python 03_compare_implementations.py
I just converted the notebook to py script

even utils.py gave me the error

  File "../mixed_res/quadtree_impl/utils.py", line 93, in <module>
    ) -> list[tuple[int, int, int, int]]:
TypeError: 'type' object is not subscriptable

**Comment by TomerRonen34** [comment]
Oh, I see. This is because I'm using built-in types for type hints, and
it's not supported by older python versions. Python 3.10 should work fine,
and probably 3.9 as well.

**Comment by Walid-Ahmed** [comment]
Thanks a lot. Sloved  after upgrade to my python
