### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'helpers'

### ISSUE THREAD

**Issue by Walid-Ahmed** [TomerRonen34/mixed-resolution-vit#6]
Hello,

With the new update, I am getting the following bug in [mixed-resolution-vit/examples/../mixed_res/tokenization/patch_embed.py]

ModuleNotFoundError: No module named 'helpers'

Can you please help?

Thanks

Walid

**Comment by TomerRonen34** [comment]
I'm sorry, apparently I made a partial push and missed a file. Could you
try again?

**Comment by Walid-Ahmed** [comment]
Thanks. it worked
